name: Update Server IP

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: 'New server IP'
        required: true
        default: '127.0.0.1'

jobs:
  update-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Replace server IP before specific server_port values
        run: |
          # Loop through all files in the root directory
          for file in $(find . -maxdepth 1 -type f); do
            echo "Checking $file..."
            
            # Use Perl to match and replace "server" before "server_port" lines
            perl -0777 -i -pe '
              s/"server":\s*"[^"]+"(?=\s*,\s*"server_port":\s*(45500|30067))/"server": "'"${{ github.event.inputs.server_ip }}"'"/g
            ' "$file"
          done

      - name: Commit and push changes
        run: |
          git add .
          git diff --cached --quiet || git commit -m "Update server IP to ${{ github.event.inputs.server_ip }}"
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
