name: Change Server in test

on:
  workflow_dispatch:
    inputs:
      new_server:
        description: 'New server value (e.g., IP or domain)'
        required: true
        default: '127.0.0.1'

jobs:
  update-server-in-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for git pull --rebase to work

      - name: Show repository contents
        run: ls -alh

      - name: Replace "server" value before specific server_port values
        run: |
          echo "Before:"
          cat test || echo "test file not found"

          awk -v new_server="${{ github.event.inputs.new_server }}" '
          {
            lines[NR] = $0
            if ($0 ~ /"server_port": (45500|30067),/) {
              for (i = NR - 1; i >= 1; i--) {
                if (lines[i] ~ /"server": "[^"]+"/) {
                  sub(/"server": "[^"]+"/, "\"server\": \"" new_server "\"", lines[i])
                  break
                }
              }
            }
          }
          END {
            for (i = 1; i <= NR; i++) print lines[i]
          }
          ' test > tmp && mv tmp test

          echo "After:"
