name: Update File

on:
  workflow_dispatch: # allows manual trigger
  push:
    branches: [main]

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make changes to a file
      run: |
        echo "Updated on $(date)" >> updates.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add updates.txt
        git commit -m "Auto update updates.txt"
        git push
      env:
        # This allows GitHub Actions to push using its token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
