name: Update server IP for selected ports

on:
  workflow_dispatch:
    inputs:
      new_server:
        description: 'New server IP or domain'
        required: true
        default: '127.0.0.1'

jobs:
  update-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code cleanly
        uses: actions/checkout@v4
        with:
          fetch-depth: 0     # get full history
          clean: true        # remove any leftover files

      - name: Update JSON via github-script
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = 'test';
            const newServer = '${{ inputs.new_server }}';

            let data = JSON.parse(fs.readFileSync(path, 'utf8'));

            function recurse(obj) {
              if (Array.isArray(obj)) {
                for (const item of obj) recurse(item);
              } else if (obj && typeof obj === 'object') {
                if ('server' in obj && 'server_port' in obj &&
                    [45500, 30067].includes(obj.server_port)) {
                  obj.server = newServer;
                }
                for (const key of Object.keys(obj)) recurse(obj[key]);
              }
            }

            recurse(data);
            fs.writeFileSync(path, JSON.stringify(data, null, 2));

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add test
          git diff --quiet --cached || git commit -m "Update server → ${{ github.event.inputs.new_server }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
