name: Update Server in Test File

on:
  workflow_dispatch:
    inputs:
      new_server:
        description: 'New server value (e.g., MY-INPUT)'
        required: true
        default: '91.223.169.169'

permissions:
  contents: write

jobs:
  update-server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Update server value in test file
      run: |
        if [ ! -f "test" ]; then
          echo "Error: 'test' file not found in repository root"
          exit 1
        fi
        sed -i 's/\("server":\s*\)"[^"]*"/\1"'"${{ inputs.new_server }}"'"/' test
        echo "Updated file contents:"
        cat test

    -
