name: Update Server IP

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: 'New server IP'
        required: true
        default: '127.0.0.1'

jobs:
  update-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Replace server IP before certain ports
        run: |
          for file in *.txt; do
            echo "Updating $file..."
            sed -i -E "/\"server_port\": (45500|30067)/{N;s/(\"server\":\s*\")[^\"]+(\"[^\n]*\n\"server_port\": (45500|30067))/\1${{ github.event.inputs.server_ip }}\2/}" "$file"
          done

      - name: Commit and push changes
        run: |
          git add *.txt
          git diff --cached --quiet || git commit -m "Update server IP to ${{ github.event.inputs.server_ip }}"
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
